version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: echo CC=g++ > make/local
      - run: python runTests.py test/unit
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: echo CC=g++ > make/local
      - run: ./runTests.py test/unit
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
